"""``aive schema`` - emit JSON Schema for the documents AIVE exchanges.

This command exists specifically to serve the AI director. The director authors
Edit Plans; handing it the real schema up front means it writes a valid plan on the
first attempt, instead of discovering the shape of the format through a sequence of
validation errors. The schema is generated from the Pydantic models, so it cannot
drift from what the validator actually accepts.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any

import typer
from pydantic import BaseModel

from app.cli.output import ExitCode, emit_error, emit_json
from app.models.edit_plan import EditPlan, EditPlanReport
from app.models.project import ProjectManifest
from app.models.speech import Transcript
from app.models.video import FootageAnalysis

app = typer.Typer(no_args_is_help=True, help="Emit JSON Schema for AIVE documents.")


class SchemaName(StrEnum):
    """The documents whose schema can be requested."""

    EDIT_PLAN = "edit-plan"
    MANIFEST = "manifest"
    TRANSCRIPT = "transcript"
    FOOTAGE = "footage"
    PLAN_REPORT = "plan-report"


_MODELS: dict[SchemaName, type[BaseModel]] = {
    SchemaName.EDIT_PLAN: EditPlan,
    SchemaName.MANIFEST: ProjectManifest,
    SchemaName.TRANSCRIPT: Transcript,
    SchemaName.FOOTAGE: FootageAnalysis,
    SchemaName.PLAN_REPORT: EditPlanReport,
}


@app.command("show")
def show(
    document: Annotated[
        SchemaName,
        typer.Argument(help="Which document's schema to emit."),
    ] = SchemaName.EDIT_PLAN,
) -> None:
    """Print the JSON Schema for a document.

    Nothing but the schema reaches stdout, so the output can be redirected straight
    into a file and fed to a validator.
    """
    model = _MODELS.get(document)
    if model is None:  # pragma: no cover - Typer rejects unknown values first
        emit_error(
            "schema.unknown",
            f"no schema named {document!r}",
            hint=f"available: {', '.join(item.value for item in SchemaName)}",
            exit_code=ExitCode.USAGE,
        )
    emit_json(model.model_json_schema())


@app.command("list")
def list_schemas() -> None:
    """List the documents that have a schema."""
    payload: dict[str, Any] = {
        "schemas": [
            {
                "name": name.value,
                "model": model.__name__,
                "doc": (model.__doc__ or "").strip().splitlines()[0],
            }
            for name, model in _MODELS.items()
        ]
    }
    emit_json(payload)


@app.command("example")
def example() -> None:
    """Print a minimal but valid Edit Plan.

    A worked example is worth more than a schema when writing a first plan: it shows
    which fields are genuinely optional and what a plausible ``reason`` looks like.
    Generated by constructing a real :class:`~app.models.edit_plan.EditPlan`, so it
    is guaranteed to validate.
    """
    from app.models.common import MediaRef, TimeRange, TransitionKind
    from app.models.edit_plan import NarrationTrack, TimelineClip, Transition

    plan = EditPlan(
        project_id="example",
        created_by="claude-code",
        narration=NarrationTrack(
            source=MediaRef(path="narration.wav"),
            kept_ranges=(TimeRange(start=0.0, end=4.2), TimeRange(start=5.1, end=11.6)),
        ),
        clips=(
            TimelineClip(
                id="c001",
                source=MediaRef(path="raw/001.mp4"),
                source_range=TimeRange(start=12.5, end=18.3),
                reason=(
                    "Wide shot of the bed being dug matches the opening line about preparing soil."
                ),
                confidence=0.9,
                scene_key="001#3",
                beat_index=0,
            ),
            TimelineClip(
                id="c002",
                source=MediaRef(path="raw/002.mp4"),
                source_range=TimeRange(start=3.0, end=8.4),
                transition_in=Transition(kind=TransitionKind.DISSOLVE, duration=0.4),
                reason=(
                    "Close-up of watering follows planting, so a dissolve reads as time passing."
                ),
                confidence=0.85,
                scene_key="002#1",
                beat_index=1,
            ),
        ),
        notes=(
            "Chronological build: prepare, plant, water. Dissolves between stages, "
            "hard cuts within a stage."
        ),
    )
    emit_json(plan)


__all__ = ["SchemaName", "app"]
