"""ASS (Advanced SubStation Alpha) output.

ASS is worth the extra complexity over SRT for two reasons: it carries styling, so the
subtitles look the same wherever they are played, and it supports karaoke timing, which
is what produces the word-by-word highlight that short-form video has made standard.

Written directly rather than through pysubs2. The format is plain text, and generating
it here means the exact ``\\k`` karaoke syntax is visible and testable rather than
buried behind a library's own model. pysubs2 stays an optional dependency, used only
where a *reader* is needed.

Two format details that are easy to get wrong and produce silently broken files:

* Colours are ``&HAABBGGRR`` — **BGR order with an alpha prefix**, not RGB. A value
  copied from a web palette comes out with red and blue swapped.
* Timestamps are ``H:MM:SS.cc`` with **centiseconds**, one digit fewer than SRT, and a
  single-digit hour with no zero padding.
"""

from __future__ import annotations

from pathlib import Path

from app.config.settings import SubtitleSettings
from app.models.common import SubtitleFormat
from app.models.edit_plan import SubtitleCue
from app.utils.logging import get_logger

logger = get_logger(__name__)

DEFAULT_STYLE_NAME = "Default"


class AssWriter:
    """A :class:`~app.subtitles.base.SubtitleWriter` producing styled ASS files."""

    def __init__(self, *, karaoke: bool = True) -> None:
        """Args:
        karaoke: Emit per-word ``\\k`` timing when a cue carries word timings.
            Turn it off for a plain styled subtitle without the highlight sweep.
        """
        self._karaoke = karaoke

    @property
    def format(self) -> SubtitleFormat:
        return SubtitleFormat.ASS

    @property
    def supports_word_timings(self) -> bool:
        return True

    def write(
        self,
        cues: tuple[SubtitleCue, ...],
        destination: Path,
        *,
        style: SubtitleSettings,
    ) -> Path:
        destination.parent.mkdir(parents=True, exist_ok=True)
        sections = [
            self._script_info(style),
            self._styles(style),
            self._events(cues),
        ]
        destination.write_text("\n".join(sections) + "\n", encoding="utf-8", newline="\n")
        logger.debug("Wrote %d ASS cue(s) to %s", len(cues), destination)
        return destination

    # -- Sections ----------------------------------------------------------- #

    @staticmethod
    def _script_info(style: SubtitleSettings) -> str:
        """The header.

        ``PlayResX``/``PlayResY`` set the coordinate space that font sizes and margins
        are expressed in. They are fixed at 1920x1080 rather than taken from the output
        settings so that a given ``font_size`` looks identical whether the video is
        rendered at 1080p or 4K; the renderer scales the whole subtitle plane with the
        frame. Without this, switching to vertical output would silently shrink text.
        """
        return "\n".join(
            (
                "[Script Info]",
                "; Generated by AIVE",
                "ScriptType: v4.00+",
                "WrapStyle: 2",  # 2 = no automatic wrapping; the builder already wrapped.
                "ScaledBorderAndShadow: yes",
                "YCbCr Matrix: TV.709",
                "PlayResX: 1920",
                "PlayResY: 1080",
                "",
            )
        )

    @staticmethod
    def _styles(style: SubtitleSettings) -> str:
        fields = (
            "Name",
            "Fontname",
            "Fontsize",
            "PrimaryColour",
            "SecondaryColour",
            "OutlineColour",
            "BackColour",
            "Bold",
            "Italic",
            "Underline",
            "StrikeOut",
            "ScaleX",
            "ScaleY",
            "Spacing",
            "Angle",
            "BorderStyle",
            "Outline",
            "Shadow",
            "Alignment",
            "MarginL",
            "MarginR",
            "MarginV",
            "Encoding",
        )
        values = (
            DEFAULT_STYLE_NAME,
            style.font_name,
            str(style.font_size),
            style.primary_colour,
            # SecondaryColour is the *un-sung* colour in karaoke: text starts in this
            # colour and flips to PrimaryColour as each word is reached.
            style.secondary_colour,
            style.outline_colour,
            style.outline_colour,
            "0",
            "0",
            "0",
            "0",
            "100",
            "100",
            "0",
            "0",
            "1",  # BorderStyle 1 = outline plus drop shadow.
            _number(style.outline),
            _number(style.shadow),
            str(style.alignment),
            str(style.margin_h),
            str(style.margin_h),
            str(style.margin_v),
            "1",
        )
        return "\n".join(
            (
                "[V4+ Styles]",
                "Format: " + ", ".join(fields),
                "Style: " + ",".join(values),
                "",
            )
        )

    def _events(self, cues: tuple[SubtitleCue, ...]) -> str:
        header = (
            "[Events]",
            "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
        )
        lines = [
            "Dialogue: 0,"
            + ",".join(
                (
                    format_timestamp(cue.range.start),
                    format_timestamp(cue.range.end),
                    cue.style_id if cue.style_id != "default" else DEFAULT_STYLE_NAME,
                    "",
                    "0",
                    "0",
                    "0",
                    "",
                    self._text(cue),
                )
            )
            for cue in cues
        ]
        return "\n".join((*header, *lines, ""))

    def _text(self, cue: SubtitleCue) -> str:
        """The dialogue text, with karaoke tags when available."""
        if self._karaoke and cue.words:
            return karaoke_text(cue)
        return escape_text(cue.text)


def karaoke_text(cue: SubtitleCue) -> str:
    """Render a cue as ``\\k``-tagged karaoke.

    Each tag's value is the duration in **centiseconds** that the preceding highlight
    lasts. Gaps between words are folded into the following word's duration rather than
    emitted as separate empty tags, which keeps the sweep continuous instead of
    stuttering between words.

    The line breaks in :attr:`~app.models.edit_plan.SubtitleCue.text` are preserved.
    They have to be: this function used to build its output from ``words`` alone, which
    silently discarded them and rendered every cue as one line. A two-line cue then ran
    off both edges of the frame - and only in karaoke mode, so ``max_chars_per_line``
    appeared to work right up until the moment it was switched on.
    """
    groups = _words_per_line(cue)
    lines: list[str] = []
    cursor = cue.range.start
    index = 0
    for count in groups:
        parts: list[str] = []
        for text, _start, end in cue.words[index : index + count]:
            # Measure from the cursor, not from the word's own start, so any gap since
            # the previous word is absorbed and the highlight sweeps continuously.
            duration_cs = max(1, round((end - cursor) * 100))
            parts.append(f"{{\\k{duration_cs}}}{escape_text(text)}")
            cursor = end
        lines.append(" ".join(parts))
        index += count
    # Already escaped word by word, so the separator is written raw.
    return "\\N".join(line for line in lines if line)


def _words_per_line(cue: SubtitleCue) -> list[int]:
    """How many of ``cue.words`` belong on each line of ``cue.text``.

    Falls back to a single line when the two disagree. ``text`` is authored and
    ``words`` are measured, so nothing guarantees they tokenise alike; when they do
    not, one long line is a cosmetic problem, whereas splitting at the wrong index
    would attach a word's highlight to the wrong syllable.
    """
    counts = [len(line.split()) for line in cue.text.splitlines() if line.strip()]
    if not counts or sum(counts) != len(cue.words):
        return [len(cue.words)]
    return counts


def escape_text(text: str) -> str:
    """Escape text for an ASS dialogue field.

    Newlines become ``\\N`` (a hard break). Braces would otherwise open an override
    block and swallow the rest of the line, so they are neutralised.
    """
    return (
        text.replace("\\", "\\\\")
        .replace("{", "\\{")
        .replace("}", "\\}")
        .replace("\r\n", "\\N")
        .replace("\n", "\\N")
    )


def format_timestamp(seconds: float) -> str:
    """Format seconds as ASS ``H:MM:SS.cc``.

    Centiseconds, truncated. Rounding up could push a cue past its successor's start.
    """
    clamped = max(0.0, seconds)
    total_cs = int(clamped * 100)
    hours, remainder = divmod(total_cs, 360_000)
    minutes, remainder = divmod(remainder, 6_000)
    secs, centis = divmod(remainder, 100)
    return f"{hours:d}:{minutes:02d}:{secs:02d}.{centis:02d}"


def _number(value: float) -> str:
    """Render a float without a trailing ``.0``, which some parsers dislike."""
    return str(int(value)) if value == int(value) else f"{value:g}"


__all__ = [
    "DEFAULT_STYLE_NAME",
    "AssWriter",
    "escape_text",
    "format_timestamp",
    "karaoke_text",
]
