"""Computing a plan review.

The statistics are arithmetic. The interesting part is :func:`editorial_notes`, which looks
for patterns that are invisible in a list of clips and unmissable in a finished video.

Each note is calibrated against a specific failure of automated editing:

* **Mechanical rhythm.** Clips of near-identical length read as a metronome. It is the most
  common tell of a plan generated by dividing narration by clip count.
* **Repeated framing.** Three consecutive shots of the same type read as laziness even when
  each was individually the best available choice.
* **Ignored footage.** Using four scenes out of forty means the edit did not look at the
  material - usually a sign the director planned from the narration alone.
* **Transition monotony.** A dissolve on every cut makes an edit feel like a slideshow; a
  hard cut everywhere can be right, but is worth noticing rather than defaulting into.

None of these block a render. They are observations, and an editor is free to disagree with
every one - which is why each carries the number it was derived from.
"""

from __future__ import annotations

import itertools
from collections import Counter
from collections.abc import Iterable

from app.models.common import Issue, Severity, ShotType, TransitionKind
from app.models.edit_plan import EditPlan
from app.models.plan_review import PlanReview, PlanStatistics, TimelineEntry
from app.models.video import FootageAnalysis
from app.utils.logging import get_logger

logger = get_logger(__name__)

REVIEW_VERSION = "review/1"

_MECHANICAL_SPREAD = 0.15
"""Relative spread below which clip lengths read as mechanical.

Fifteen percent: a human edit varies shot length with content, so a set of clips within a
sixth of each other almost always means the durations were computed rather than chosen.
"""

_MAX_SAME_SHOT_RUN = 3
"""Consecutive clips of one shot type before the framing stops varying visibly."""

_FOOTAGE_USE_FLOOR = 0.25
"""Fraction of available scenes below which the edit has ignored the material."""

_MIN_CLIPS_FOR_RHYTHM = 4
"""Below this there is no rhythm to judge - three clips cannot be monotonous."""


def build_review(
    plan: EditPlan,
    *,
    footage: FootageAnalysis | None = None,
) -> PlanReview:
    """Render a plan for review and attach editorial observations.

    ``footage`` is optional: without it the shot-type and footage-usage notes cannot be
    produced, and the review says less rather than guessing.
    """
    shot_types = _shot_types(footage)
    timeline = _timeline(plan, shot_types)
    statistics = compute_statistics(plan, timeline)

    return PlanReview(
        project_id=plan.project_id,
        created_by=plan.created_by,
        is_placed=plan.is_placed,
        statistics=statistics,
        timeline=timeline,
        notes=editorial_notes(plan, statistics, timeline, footage=footage),
        plan_notes=plan.notes,
    )


def _shot_types(footage: FootageAnalysis | None) -> dict[str, ShotType]:
    """Scene key to shot type, so the review can report framing.

    A plan records ``scene_key`` but not shot type - the plan is deliberately decoupled from
    the analysis - so the mapping has to be rebuilt here from the footage document.
    """
    if footage is None:
        return {}
    return {scene.key: scene.shot_type for scene in footage.scenes}


def _timeline(plan: EditPlan, shot_types: dict[str, ShotType]) -> tuple[TimelineEntry, ...]:
    entries: list[TimelineEntry] = []
    for order, clip in enumerate(plan.clips):
        transition = clip.transition_in
        entries.append(
            TimelineEntry(
                clip_id=clip.id,
                order=order,
                source=clip.source,
                source_range=clip.source_range,
                timeline_range=clip.timeline_range if clip.is_placed else None,
                transition_in=transition.kind if transition else TransitionKind.CUT,
                transition_duration=transition.duration if transition else 0.0,
                shot_type=shot_types.get(clip.scene_key or "", ShotType.UNKNOWN),
                scene_key=clip.scene_key,
                beat_index=clip.beat_index,
                reason=clip.reason,
                confidence=clip.confidence,
            )
        )
    return tuple(entries)


def compute_statistics(plan: EditPlan, timeline: tuple[TimelineEntry, ...]) -> PlanStatistics:
    """Measure a plan's shape.

    Takes the timeline rather than reaching for the footage analysis itself: shot types are
    already resolved onto the entries, so there is only one place that mapping happens.
    """
    durations = [clip.timeline_duration for clip in plan.clips]
    total = plan.timeline_duration

    transitions = Counter(entry.transition_in.value for entry in timeline)
    shots = Counter(entry.shot_type.value for entry in timeline)
    scenes = {clip.scene_key for clip in plan.clips if clip.scene_key}

    return PlanStatistics(
        clip_count=len(plan.clips),
        total_duration=total,
        mean_clip_duration=sum(durations) / len(durations) if durations else 0.0,
        median_clip_duration=_median(durations),
        shortest_clip=min(durations, default=0.0),
        longest_clip=max(durations, default=0.0),
        # Per minute of finished video, so it is comparable across projects.
        cuts_per_minute=(len(plan.clips) / total * 60.0) if total > 0 else 0.0,
        transition_counts=dict(transitions),
        shot_type_counts=dict(shots),
        distinct_sources=len({clip.source for clip in plan.clips}),
        distinct_scenes=len(scenes),
        longest_same_shot_run=longest_run(
            entry.shot_type for entry in timeline if entry.shot_type is not ShotType.UNKNOWN
        ),
        narration_duration=(
            plan.narration.timeline_duration if plan.narration is not None else None
        ),
        subtitle_count=len(plan.subtitles),
    )


def longest_run(values: Iterable[object]) -> int:
    """Longest run of consecutive equal values.

    ``UNKNOWN`` shot types are filtered out by the caller rather than here: with the
    classical vision provider most scenes are unknown, and a run of "unknown" says nothing
    about framing.
    """
    return max((sum(1 for _ in group) for _, group in itertools.groupby(values)), default=0)


def editorial_notes(
    plan: EditPlan,
    statistics: PlanStatistics,
    timeline: tuple[TimelineEntry, ...],
    *,
    footage: FootageAnalysis | None = None,
) -> tuple[Issue, ...]:
    """Observations a second pair of eyes would make."""
    notes: list[Issue] = []

    notes.extend(_rhythm_notes(statistics))
    notes.extend(_framing_notes(statistics))
    notes.extend(_transition_notes(statistics))
    notes.extend(_footage_use_notes(statistics, footage))
    notes.extend(_provenance_notes(plan, timeline))
    notes.extend(_coverage_notes(statistics))

    return tuple(notes)


def _rhythm_notes(statistics: PlanStatistics) -> list[Issue]:
    if statistics.clip_count < _MIN_CLIPS_FOR_RHYTHM or statistics.mean_clip_duration <= 0:
        return []

    spread = (statistics.longest_clip - statistics.shortest_clip) / statistics.mean_clip_duration
    if spread < _MECHANICAL_SPREAD:
        return [
            Issue(
                code="review.mechanical_rhythm",
                severity=Severity.WARNING,
                message=(
                    f"all {statistics.clip_count} clips are within "
                    f"{spread:.0%} of each other in length "
                    f"({statistics.shortest_clip:.1f}s to {statistics.longest_clip:.1f}s)"
                ),
                hint="a constant shot length reads as a metronome; vary it with the content",
            )
        ]
    return []


def _framing_notes(statistics: PlanStatistics) -> list[Issue]:
    if statistics.longest_same_shot_run >= _MAX_SAME_SHOT_RUN:
        return [
            Issue(
                code="review.repeated_framing",
                severity=Severity.WARNING,
                message=(
                    f"{statistics.longest_same_shot_run} consecutive clips share one shot type"
                ),
                hint="wide to establish, medium for action, close-up for detail",
            )
        ]
    return []


def _transition_notes(statistics: PlanStatistics) -> list[Issue]:
    counts = statistics.transition_counts
    total = sum(counts.values())
    if total < _MIN_CLIPS_FOR_RHYTHM:
        return []

    notes: list[Issue] = []
    cuts = counts.get(TransitionKind.CUT.value, 0)
    non_cut = total - cuts

    if non_cut == total:
        notes.append(
            Issue(
                code="review.every_cut_is_a_transition",
                severity=Severity.WARNING,
                message=f"all {total} joins use a transition, none is a hard cut",
                hint="a dissolve should mean time passed; everywhere it means slideshow",
            )
        )
    elif len({kind for kind, count in counts.items() if count}) == 1 and non_cut == 0:
        notes.append(
            Issue(
                code="review.no_transitions",
                severity=Severity.INFO,
                message=f"every one of the {total} joins is a hard cut",
                hint="correct within continuous action; consider a dissolve where a stage changes",
            )
        )
    return notes


def _footage_use_notes(statistics: PlanStatistics, footage: FootageAnalysis | None) -> list[Issue]:
    if footage is None:
        return []

    available = len(footage.scenes) - len(footage.suppressed_scene_keys)
    if available <= 0 or statistics.distinct_scenes == 0:
        return []

    used_fraction = statistics.distinct_scenes / available
    if used_fraction < _FOOTAGE_USE_FLOOR:
        return [
            Issue(
                code="review.footage_underused",
                severity=Severity.INFO,
                message=(
                    f"{statistics.distinct_scenes} of {available} usable scene(s) appear in "
                    f"the plan ({used_fraction:.0%})"
                ),
                hint="worth a second look at what was left out",
            )
        ]
    return []


def _provenance_notes(plan: EditPlan, timeline: tuple[TimelineEntry, ...]) -> list[Issue]:
    """Notes about the plan's own record of its decisions."""
    notes: list[Issue] = []

    if plan.created_by == "heuristic":
        notes.append(
            Issue(
                code="review.heuristic_plan",
                severity=Severity.WARNING,
                message="this plan was generated heuristically, not edited",
                hint=(
                    "clips were chosen by duration and quality; nothing reflects what the "
                    "footage shows. Revise the selections and the reason fields."
                ),
            )
        )

    unexplained = [entry.clip_id for entry in timeline if len(entry.reason.split()) < 4]
    if unexplained:
        listed = ", ".join(unexplained[:5])
        more = f" and {len(unexplained) - 5} more" if len(unexplained) > 5 else ""
        notes.append(
            Issue(
                code="review.thin_reasons",
                severity=Severity.INFO,
                message=f"{len(unexplained)} clip(s) have a very short reason: {listed}{more}",
                hint="the reason is what a reviewer reads; one sentence beats one word",
            )
        )

    without_scene = sum(1 for entry in timeline if entry.scene_key is None)
    if without_scene and without_scene == len(timeline):
        notes.append(
            Issue(
                code="review.no_provenance",
                severity=Severity.INFO,
                message="no clip records a scene_key, so nothing links back to the analysis",
                hint="set scene_key so a reviewer can find the shot you meant",
            )
        )
    return notes


def _coverage_notes(statistics: PlanStatistics) -> list[Issue]:
    delta = statistics.coverage_delta
    if delta is None:
        return []
    if delta < -0.5:
        return [
            Issue(
                code="review.narration_uncovered",
                severity=Severity.WARNING,
                message=(
                    f"the picture is {-delta:.1f}s shorter than the narration, so the video "
                    "ends on black while the voice continues"
                ),
                hint="add or lengthen clips",
            )
        ]
    if delta > 3.0:
        return [
            Issue(
                code="review.long_tail",
                severity=Severity.INFO,
                message=f"the picture runs {delta:.1f}s past the end of the narration",
                hint="fine as a deliberate tail; trim it otherwise",
            )
        ]
    return []


def _median(values: list[float]) -> float:
    if not values:
        return 0.0
    ordered = sorted(values)
    middle = len(ordered) // 2
    if len(ordered) % 2 == 1:
        return ordered[middle]
    return (ordered[middle - 1] + ordered[middle]) / 2.0


__all__ = ["REVIEW_VERSION", "build_review", "compute_statistics", "editorial_notes", "longest_run"]
